FROM python:3.11-slim

# Evita geração de .pyc
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Instala dependências do sistema necessárias para psycopg2
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copia dependências
COPY requirements-fastapi.txt .

RUN pip install --no-cache-dir -r requirements-fastapi.txt

# Copia código
COPY . .

# Porta padrão da API
EXPOSE 8000

# Executa FastAPI
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

